### ISSUE TITLE
hello?

### ISSUE THREAD

**Issue by mhj9030** [MatthiasWinzeler/scam#1]
Good morning? [Https://github.com/MatthiasWinzeler/scam] project,

How do I install the Windows server? plz help me

**Comment by emmanuelbenoist** [comment]
The installation instructions are in the file "README.md". They are written for a Linux environment. We do not recommand using a Windows server for hosting a scam server.

**Comment by mhj9030** [comment]
I should be sure to install the Windows Server

Is there a way?
