### ISSUE TITLE
what is commned line?

### ISSUE THREAD

**Issue by mhj9030** [MatthiasWinzeler/scam#2]
*/10 * * * * /path/to/.phpbrew/php/php-5.4.34/bin/php /path/to/scam/app/run.php 

do not found app/run.php ...

**Comment by MatthiasWinzeler** [comment]
You are right, the command line was wrong - there is no `run.php`, it is `cli.php run` instead. 
I fixed the README: https://github.com/MatthiasWinzeler/scam/commit/284f608ed36f9719efa55d5d9d2c2754e42dfe9a
